/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  homeSidebar: ['index'],
  stringsSidebar: [{type: 'autogenerated', dirName: 'strings'}],
  bridgesSidebar: [{type: 'autogenerated', dirName: 'bridges'}],
  pegsSidebar: [{type: 'autogenerated', dirName: 'pegs'}],
  fingerboardsSidebar: [{type: 'autogenerated', dirName: 'fingerboards'}],
  endpinsSidebar: [{type: 'autogenerated', dirName: 'endpins'}],
  tailpiecesSidebar: [{type: 'autogenerated', dirName: 'tailpieces'}],
  nutsSidebar: [{type: 'autogenerated', dirName: 'nuts'}],
  saddlesSidebar: [{type: 'autogenerated', dirName: 'saddles'}],
  soundpostsSidebar: [{type: 'autogenerated', dirName: 'soundposts'}],
  tailgutsSidebar: [{type: 'autogenerated', dirName: 'tailguts'}],
  bowsSidebar: [{type: 'autogenerated', dirName: 'bows'}],
  rosinSidebar: [{type: 'autogenerated', dirName: 'rosin'}],
  casesSidebar: [{type: 'autogenerated', dirName: 'cases'}],
};

module.exports = sidebars;
