# 基本情報
url: "https://arscombinatoria.github.io"
baseurl: "/cello-parts-log"
title: "チェロのパーツ交換についての備忘録"
locale: ja-JP
repository: "arscombinatoria/cello-parts-log"

# テーマ＆プラグイン
theme: "minimal-mistakes-jekyll"
minimal_mistakes_skin: "air"
plugins:
  - jekyll-feed
  - jekyll-include-cache

# コレクション定義
collections:
  strings:
    output: true
    permalink: /strings/:path/
  bridges:
    output: true
    permalink: /bridges/:path/
  pegs:
    output: true
    permalink: /pegs/:path/
  fingerboards:
    output: true
    permalink: /fingerboards/:path/
  endpins:
    output: true
    permalink: /endpins/:path/
  tailpieces:
    output: true
    permalink: /tailpieces/:path/
  nuts:
    output: true
    permalink: /nuts/:path/
  saddles:
    output: true
    permalink: /saddles/:path/
  soundposts:
    output: true
    permalink: /soundposts/:path/
  tailguts:
    output: true
    permalink: /tailguts/:path/
  string_makers:
    output: true
    permalink: /strings/manufacturers/:path/

# Front Matter Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      sidebar: null
      classes: wide
      footer_scripts:
        - /assets/js/no-sidebar.js
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      sidebar: null
      classes: wide
      footer_scripts:
        - /assets/js/no-sidebar.js

  # 各コレクションをグリッド表示
  - scope:
      path: ""
      type: strings
    values:
      layout: single
      author_profile: false
      sidebar: null
      classes: wide
      entries_layout: grid
  - scope:
      path: ""
      type: bridges
    values:
      layout: single
      author_profile: false
      sidebar: null
      classes: wide
      entries_layout: grid
  - scope:
      path: ""
      type: pegs
    values:
      layout: single
      author_profile: false
      sidebar: null
      classes: wide
      entries_layout: grid
  - scope:
      path: ""
      type: fingerboards
    values:
      layout: single
      author_profile: false
      sidebar: null
      classes: wide
      entries_layout: grid
  - scope:
      path: ""
      type: endpins
    values:
      layout: single
      author_profile: false
      sidebar: null
      classes: wide
      entries_layout: grid
  - scope:
      path: ""
      type: tailpieces
    values:
      layout: single
      author_profile: false
      sidebar: null
      classes: wide
      entries_layout: grid
  - scope:
      path: ""
      type: nuts
    values:
      layout: single
      author_profile: false
      sidebar: null
      classes: wide
      entries_layout: grid
  - scope:
      path: ""
      type: saddles
    values:
      layout: single
      author_profile: false
      sidebar: null
      classes: wide
      entries_layout: grid
  - scope:
      path: ""
      type: soundposts
    values:
      layout: single
      author_profile: false
      sidebar: null
      classes: wide
      entries_layout: grid
  - scope:
      path: ""
      type: tailguts
    values:
      layout: single
      author_profile: false
      sidebar: null
      classes: wide
      entries_layout: grid
  - scope:
      path: ""
      type: string_makers
    values:
      layout: single
      author_profile: false
      sidebar: null
      classes: wide
      entries_layout: grid
